export const DISPLAY_INFO = "DISPLAY_INFO";
export const ADD_EMAIL = "ADD_EMAIL";
export const ADD_TEL = "ADD_TEL";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const HANDLE_EMAIL_CHANGE = "HANDLE_EMAIL_CHANGE";
export const HANDLE_PHONENO_CHANGE = "HANDLE_PHONENO_CHANGE";
export const VALIDATE = "VALIDATE";